/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

package main

import "fmt"

func main() {
	f1 := 1
	f2 := 1
	sum := 0
	for f2 < 4000000 {
		if f2%2 == 0 {
			sum += f2
		}
		f1, f2 = f2, f1+f2
	}
	fmt.Printf("The sum of the even-valued fibonacci terms = %d", sum)
}
